name: release

on:
  push:
    branches:
      - "**"
      - "!renovate/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: "bangumi/chii"

    steps:
      - uses: actions/checkout@v3

      - run: |
          LONG_TAG=${{ hashFiles('yarn.lock') }}

          echo "TAG_HASH=1-${LONG_TAG:0:10}" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: |
          if ! docker pull ghcr.io/trim21/bangumi-workers:base-${TAG_HASH}; then
            echo "build base docker image"
            docker build -t ghcr.io/trim21/bangumi-workers:base-${TAG_HASH} -f base.dockerfile .
            docker push ghcr.io/trim21/bangumi-workers:base-${TAG_HASH}
          fi

          docker tag ghcr.io/trim21/bangumi-workers:base-${TAG_HASH} base-image

          docker build -t ghcr.io/trim21/bangumi-workers:latest .

      - run: docker push ghcr.io/trim21/bangumi-workers:latest
